### ISSUE TITLE
AESRC2020 Dataset Access

### ISSUE THREAD

**Issue by PiotrDabkowski** [R1ckShi/AESRC2020#4]
Thanks a lot for this project. We would like to try our model on this dataset and compare to results by other teams. Is this dataset (AESRC2020) available anywhere? The [Interspeech2020 paper](https://arxiv.org/abs/2102.10233) claims that the dataset will be open ("open datasets, baselines").

**Comment by R1ckShi** [comment]
you can contect data company datatang through email _services@datatang.com_, and follow their data using rules to get the dataset.
